title: lmassa
author: Ludovico Massaccesi
email: 62757383+lmassach@users.noreply.github.com
description: My personal webpages (in beta)

minima:
  skin: dark

theme: minima

plugins:
 - jekyll-titles-from-headings
