title: lmassa
author: Ludovico Massaccesi
email: 62757383+lmassach@users.noreply.github.com
description: My personal webpages

minima:
  skin: dark

remote_theme: jekyll/minima

plugins:
 - jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false
